<?php
/** @var \PrivacyGate\PaymentGateway\Block\Adminhtml\Order\View\Details $block */
if ($block->isPaymentMadeInPrivacyGate()) {
    $details = $block->getCoinsDetail();
    ?>
    <div class="verticalSpace"><b>PrivacyGate charge code: </b> <?php echo $details['code'] ?></div>
    <?php
    if ($details['transactionId'] !== null) { ?>
        <div class="verticalSpace"><b>PrivacyGate status: </b> <?php echo $details['status'] ?></div>
        <div class="verticalSpace"><b>Expected amount: </b> <?php echo $details['expectedCoins'] ?></div>
        <div class="verticalSpace"><b>Paid amount: </b> <?php echo $details['amount'] ?></div>
        <div class="verticalSpace"><b>Paid amount( In order currency ): </b>
            <?php echo $details['totalPaid'] . ' ' . $details['orderPlacedCurrency']; ?>
        </div>
        <div class="verticalSpace"><b>Transaction id: </b> <?php echo $details['transactionId'] ?></div>
        <?php
    }
} ?>
